### ISSUE TITLE
Commands are wrong

### ISSUE THREAD

**Issue by fungalcofe** [insipx/kak-crosshairs#15]
Hi,

Commands shown in README are wrong. I installed it and `crosshairs` activate both highlight.
I've yet found other commands.

**Comment by insipx** [comment]
Hey! Sorry about this. Forgot to update it after merging the last PR. I have updated the Readme to reflect the new commands (they are more succinct then before)

`crosshairs` will activate both
`cursorline` activates just highlighting for the current line
`cursorcolumn` activates just highlighting for the current column
