### ISSUE TITLE
Proper hook to enable by default

### ISSUE THREAD

**Issue by FlyingWombat** [insipx/kak-crosshairs#9]
I'm trying to figure out what the proper way to enable crosshairs by default is.  
I'm new to Kakoune, so I'm not all that familiar with the various hooks.  
After a bit of trying to figure it out, I figured I should probably post an issue about it.

What happens is: after switching buffers, the highlighted lines don't change; they get "stuck".
- With `hook global WinCreate .* %{ crosshairs }` the crosshairs get stuck after switching to a new buffer.
- `hook global WinDisplay .* %{ crosshairs }` almost works, but isn't enabled for new buffers opened in the same window. And, oddly, running `:crosshairs` seems to affect all buffers. So, if I open Kakoune, the crosshairs are there. Then if I open another buffer, the crosshairs are not in the new one, but still in the old one. Then, if I run `:crosshairs`, they swap: the new has them enabled, and they are stuck in the old.
- `hook global BufCreate .* %{ crosshairs }` doesn't work

Could you help me out with a way to enable this by default?

#### Edit
I think I figured out something that works:
```
hook -once global WinCreate .* %{ crosshairs }
```

**Comment by FlyingWombat** [comment]
Closing, 'cause I figured it out.  
Feel free to comment if you know of something better.

**Comment by eikenb** [comment]
Maybe consider adding this to the README. I had a similar question and used the solution presented here.

**Comment by fent** [comment]
for anyone wondering how to show crosshairs only when the window is focused

```
hook global FocusIn .* crosshairs
hook global FocusOut .* crosshairs
hook global ClientClose .* crosshairs
```
